name: Build

on:
  push:
    branches: [ "v3" ]
  pull_request:
    branches: [ "v3" ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg-cache
  VCPKG_ROOT: C:\vcpkg

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Install
      run: |
        cmake --install ${{ github.workspace }}/build --component "components" --config ${{ env.BUILD_TYPE }} --prefix ${{ github.workspace }}/ReleaseBuild
    - name: Upload Artifact
      uses: actions/upload-artifact@v5
      with:
        name: ${{ github.event.repository.name }}
        path: ${{ github.workspace }}/ReleaseBuild